# Generated by Django 4.2.7 on 2023-11-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdouct_name',
            new_name='product_name',
        ),
    ]
